services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ol
      POSTGRES_PASSWORD: ol
      POSTGRES_DB: olar
    ports:
        - "5433:5432"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - "2222:8080"
